[FE] feat: add a board to display saved chat and transcribed text from stt
jungle-6-3/code-sync-fe pull request #117
Opened 2024-11-09 13:46 UTC by Y-minseong

## 주요 변경사항
- 저장한 채팅(voice채팅, 일반 채팅)을 저장한 후 이전 회의록에서 보여주기.
## 리뷰어에게...
- 더 원하시는 사항 있으면 추가하겠습니다.
## 관련 이슈

- closes #114

2024-11-09 16:27 UTC, loopy-lim requested changes
몇가지만 수정하시면 좋을 것 같습니다

2024-11-09 16:27 UTC, loopy-lim commented on src/components/Conversation/Save/Chatting.tsx
> +  });
function이 아닌 화살표함수를 쓰면 저희 코드에 더 맞는 코드가 될 것 같습니다

2024-11-09 16:27 UTC, loopy-lim commented on src/components/Conversation/Save/Chatting.tsx
> +          <h1 className="mb-4 text-center text-2xl font-bold">Voice Text</h1>
보통 h1은 페이지에 하나만 있습니다

2024-11-09 16:27 UTC, loopy-lim commented on src/components/Conversation/Save/Chatting.tsx
> +              }`}
lib안에 있는 cn에 대해서 찾아보시고 적용하시면 좋겠습니다

2024-11-10 06:27 UTC, pigpgw approved these changes

2024-11-10 06:27 UTC, pigpgw commented on src/components/Conversation/Save/Chatting.tsx
> +              }`}
clsx 라이브러리로 className 조건부 쉽게 하기
- [링크](https://www.npmjs.com/package/clsx)

2024-11-10 07:23 UTC, Y-minseong commented on src/components/Conversation/Save/Chatting.tsx
> +  });
넵 ! 수정하겠습니다 !

2024-11-10 07:25 UTC, Y-minseong commented on src/components/Conversation/Save/Chatting.tsx
> +          <h1 className="mb-4 text-center text-2xl font-bold">Voice Text</h1>
수정하겠습니다 !

2024-11-10 07:54 UTC, Y-minseong commented on src/components/Conversation/Save/Chatting.tsx
> +              }`}
두분 말씀 듣고 clsx와 cn에 대해 좀 알아봤는데 clsx도 정말 좋은 것이지만 cn과 tailwind의 궁합이 좋다고 하네요 ! 
cn이 tailwind에서의 중복 클래스문제를 해결해준다고 해요 ! 
그래서 cn으로 변경했습니다 !

2024-11-10 08:49 UTC, loopy-lim commented on src/components/Conversation/Save/Chatting.tsx
> +              }`}
cn은 clsx로 만든 것이라, 사실 차이가 없긴 해용

2024-11-10 08:51 UTC, loopy-lim approved these changes
좋아용 꼭 배열일 이유는 없어서 그것만 제거해주면 될것 같아요

2024-11-10 08:51 UTC, loopy-lim commented on src/components/Conversation/Save/Chatting.tsx
> +              ])}
배열로 안넣어도 된답니다~

2024-11-10 09:55 UTC, Y-minseong commented on src/components/Conversation/Save/Chatting.tsx
> +              ])}
수정하겠습니다 ~~ 감사합니다 ㅎㅎ

2024-11-10 11:11 UTC, merged