fix: Enhance Real-time User Location Tracking and Cursor Visibility in Collaborative Environment
jungle-6-3/code-sync-fe pull request #118
Opened 2024-11-09 14:38 UTC by pigpgw

## 주요 변경사항
- 같은 에디터에서 작업 후 다른 파일에서 편집을 하면 다른 파일에서 작업하는 커서 잔상이 순간순간 이전 파일에 계속 보이는 문제가 발생함
## 리뷰어에게...

## 관련 이슈

closes

2024-11-09 16:31 UTC, loopy-lim requested changes
더 깔끔해진 것 같습니다.
다만 react스럽지 않는 모습이 조금 있어 이는 고쳐주시면 좋겠습니다

2024-11-09 16:31 UTC, loopy-lim commented on src/components/Frame/MainFrame.tsx
> +  };
먼가 함수형처럼 쓰셨네요. 이럴때는 hidden이라는 전역적인 css를 만든 다음 추가하는 것도 좋습니다.

2024-11-09 16:31 UTC, loopy-lim commented on src/components/Frame/MainFrame.tsx
> +    });
꺌끔해진 모습이 좋습니다. 다만 `position ?? null`이라는 코드는 잘 이해가 가지 않는데 특별히 쓰신 이유가 있으실까요?

2024-11-09 16:31 UTC, loopy-lim commented on src/components/Frame/MainFrame.tsx
> +          );
먼가 css를 따로 빼신것을 보아하니.... 마음이 조금 아픕니다...
이를 react스럽게 승화시키는 방법이 없을까요?

2024-11-09 16:31 UTC, loopy-lim commented on src/components/Frame/MainFrame.tsx
> +      removeAllCursorStle();
먼가 필요 없는 곳까지 들어가는 것이 아닐까요?

2024-11-09 19:48 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +    });
현재 로직에서는 Monaco Editor에서 편집할 때 Monaco 라이브러리의 함수를 사용해 커서 정보를 가져오도록 했습니다. 다만, Draw Board에서는 커서 정보가 필요하지 않아서 position이 undefined일 경우 null로 설정하여 초기화했습니다. 이렇게 하면 에디터와 드로우 보드를 전환할 때마다 커서 정보가 리셋되게 하고자 하였습니다. 근데 리뷰에대한 답글을 달면서 생각해보니 커서 위치로 무언가 미리보기 비슷한걸 해볼까 했었는데 그걸 안할거면 구지 필요한가? 라는 생각이 갑자기 드네요...

2024-11-09 19:49 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +  };
감사합니다 내일 적용해보도록 하겠습니다!

2024-11-09 19:50 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +          );
컴포넌트화 해보갰습니다. 사실 저도 하면서 이렇게하면 혼나겠지 라는 생각이 조금 들긴 했었... 좌송합니다

2024-11-09 19:52 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +      removeAllCursorStle();
아직 클린업의 이해도가 부족한 것 같습니다. 더 공부해서 오겠습니다 감사합니다

2024-11-09 19:57 UTC, pigpgw reviewed
소중한리뷰 감사핮니다 내일 반영하고 말씀드리겠습니다

2024-11-10 08:35 UTC, pigpgw reviewed
소인을 죽여주십시오...

2024-11-10 08:35 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +    });
고민끝에 cursor positon 부분은  현재 기능구현상 필요하지 않고 지금처럼 혼란을 줄 수 있고, 불필요하다고 생각되어 삭제하였습니다.  감사합니다.

2024-11-10 08:35 UTC, pigpgw commented on src/components/File/PRBottomFileExplorer.tsx
> +                    loading="lazy"
[103번 PR](https://github.com/jungle-6-3/code-sync-fe/pull/103)에 남겨주신 성능 관점에서의 속성을 적용했습니다.

2024-11-10 08:35 UTC, pigpgw commented on src/lib/file.ts
> +  return fileList.length > 0 ? fileList[fileList.length -1] : defaultFile
[103번 PR](https://github.com/jungle-6-3/code-sync-fe/pull/103)에 남겨주신 함수화를 최대한 진행해 보았습니다. 유틸리티 관련해서 최대한 분리하도록 노력하였습니다.

2024-11-10 08:35 UTC, pigpgw commented on src/lib/yjs.ts
> +`;
아직 해당 부분은 어려움을 겪고있어서...

2024-11-10 08:37 UTC, pigpgw commented on src/components/Frame/MainFrame.tsx
> +    });
현재 기능으로서는 커서의 위치가 불필요하다고 생각되어 삭제하였습니다.

2024-11-10 08:55 UTC, loopy-lim approved these changes
좋네용!!

2024-11-10 08:55 UTC, loopy-lim commented on src/components/File/PRBottomFileExplorer.tsx
> +                    loading="lazy"
좋네용

2024-11-10 08:55 UTC, loopy-lim commented on src/components/Frame/MainFrame.tsx
> +    });
넵!! 감사합니다

2024-11-10 08:55 UTC, loopy-lim commented on src/lib/file.ts
> +  return fileList.length > 0 ? fileList[fileList.length -1] : defaultFile
넹  ㅠㅠㅠ 사실 저도 어떻게 다루어야 할지 참... 힘드네요

2024-11-10 08:55 UTC, loopy-lim commented on src/lib/yjs.ts
> +`;
내일 함 같이 봐보죠!

2024-11-10 10:30 UTC, pigpgw commented on src/lib/file.ts
> +  return fileList.length > 0 ? fileList[fileList.length -1] : defaultFile
제가 죄송합니다.

2024-11-10 12:22 UTC, merged