Feat/ add PreviousMeetingAPI, pagination
jungle-6-3/code-sync-fe pull request #64
Opened 2024-10-31 14:04 UTC by Y-minseong

## 주요 변경사항
- 이전 회의록 api로 데이터 받아오고 게시판 만들었고, 페이지네이션 구현했습니다.
## 리뷰어에게...
- 현재 페이지네이션으로 한페이지에 2개의 데이터만 보여줄 수 있게 구현해놓았습니다. 아직 여러값의 데이터를 받지 못해 테스트용으로만 설정해놓고 후에 수정하겠습니다. 
## 관련 이슈

- closes #63

2024-11-01 01:56 UTC, loopy-lim requested changes
몇가지 고치면 좋을만한 것들이 있어요.
예를 들면 게시판을 만들때 다른 곳에서는 어떻게 만들었는지 한번쯤은 고민해주시면 좋을 것 같아요

2024-11-01 01:56 UTC, loopy-lim commented on src/apis/conversation/dtos.ts
> +  participantPk: number;
놀라라.... 추후에 BE가 변경될 때 이야기 해주세요~

2024-11-01 01:56 UTC, loopy-lim commented on src/apis/conversation/dtos.ts
> +  finishedAt: Date;
일단 BE에서 올 때는 대부분 string입니다. 이렇게 작성하면 안될꺼에요

2024-11-01 01:56 UTC, loopy-lim commented on src/components/Users/Login.tsx
> +import useLoginQuery from "@/hooks/Users/useLoginMutation";
잘 하셨네요
useLoginQuery가 아니라 useLoginMutation으로 바꾸어 주세요

2024-11-01 01:56 UTC, loopy-lim commented on src/components/Users/SignUp.tsx
> +import usePostData from "@/hooks/Users/useSignUpMutation";
PostData가 왜 useSignUp에 있죠?
postData가 무엇을 하는 친구일까요?

2024-11-01 01:56 UTC, loopy-lim commented on src/components/useLogoutButton.tsx
> +  const onLogOut = async () => {
LogOut에서 Logout으로 바꾸면 더 읽기 편할것 같아요

2024-11-01 01:56 UTC, loopy-lim commented on src/hooks/Conversation/usePreviousMeetingQuery.tsx
> +    queryFn: previousMeetingApi,
앞에 post인지 get인지만 알 수 있게 알려주세요~

2024-11-01 01:56 UTC, loopy-lim commented on src/pages/PreviousMeeting.tsx
> +  const pageData = conversation.slice(startPage, endPage);
이런것은 안에서 하는 것보다 lib으로 빼서 계산하는 것이 더 효율적일꺼에요

2024-11-01 01:56 UTC, loopy-lim commented on src/pages/PreviousMeeting.tsx
> +                onClick={() => onNextPage(Math.max(1, currentPage - 1))}
href와 onClick이 함께 있는 것은 독특한데 왜 그럴까요?

2024-11-01 01:56 UTC, loopy-lim commented on src/pages/conversation/ConversationChatting.tsx
> +}
이것또한 어떻게 빼면 좋을까요? 다른 곳에서 사용해도 되긴하는데, 여기에 둔다면 그 이유는 무엇일까요? 아래 댓글에 써주세요

2024-11-01 12:48 UTC, loopy-lim approved these changes
구우웃~ 💯

2024-11-01 12:48 UTC, loopy-lim commented on src/pages/PreviousRoom.tsx
> +                  <TableCell>3일 전</TableCell>
나중에 고쳐주실꺼죠?

2024-11-01 12:48 UTC, loopy-lim commented on src/pages/PreviousRoom.tsx
> +      </div>
이런것도 나중에 component로 빼면 이해하기 편할꺼 같아요

2024-11-01 12:48 UTC, loopy-lim commented on src/pages/PreviousRoom.tsx
> +  }
데이터가 없을때도 로딩중이지만, 다른 것도 한번 신경써주세요

2024-11-01 12:48 UTC, loopy-lim commented on src/pages/PreviousRoom.tsx
> +  const pageCount = 8;
이런 특정 값들은 매직넘버라고 불리는데, 이들은 상수값으로 관리하는 것이라서 대부분 이 함수 밖에서 선언해요

`const PAGE_COUNT = 8;`과 같이 말이죠

2024-11-01 12:48 UTC, merged

2024-11-02 03:19 UTC, pigpgw commented on src/pages/PreviousRoom.tsx
> +  // const [currentPage, setCurrentPage] = useState(1);
.

2024-11-02 03:19 UTC, pigpgw commented on src/pages/PreviousRoom.tsx
> +  const pageCount = 8;
[매직 넘버와 매직 스트링](https://dev.to/ruben_alapont/magic-numbers-and-magic-strings-its-time-to-talk-about-it-ci2)

2024-11-02 03:19 UTC, pigpgw commented on src/pages/PreviousRoom.tsx
> +  }
채승님 말씀에 연장선인데 tanstack query에서 제공해주는 기능을 활용해보면 좋을 것 같습니다.!

> [카카오페이 프론트엔드 개발자들이 React Query를 선택한 이유](https://tech.kakaopay.com/post/react-query-1/) 의 "React Query를 쓰고 이게 편해졌다" 부분

2024-11-03 14:15 UTC, Y-minseong commented on src/apis/conversation/dtos.ts
> +  participantPk: number;
알겠습니다 !!

2024-11-03 14:18 UTC, Y-minseong commented on src/apis/conversation/dtos.ts
> +  finishedAt: Date;
수정 했습니다 !!

2024-11-03 14:19 UTC, Y-minseong commented on src/components/Users/Login.tsx
> +import useLoginQuery from "@/hooks/Users/useLoginMutation";
수정했습니다 ! 감사합니다 ~~

2024-11-03 15:06 UTC, Y-minseong commented on src/components/Users/SignUp.tsx
> +import usePostData from "@/hooks/Users/useSignUpMutation";
그러게요 .. 과거의 저는 바보여서 네이밍을 바보같이 해놨습니다.. 하지만 현재의 제가 수정했습니다 현재의 저를 만드신 채승님께 치얼스

2024-11-03 15:06 UTC, Y-minseong commented on src/components/useLogoutButton.tsx
> +  const onLogOut = async () => {
전부 수정했습니다 !

2024-11-03 15:07 UTC, Y-minseong commented on src/hooks/Conversation/usePreviousMeetingQuery.tsx
> +    queryFn: previousMeetingApi,
수정했습니다 !!

2024-11-03 15:08 UTC, Y-minseong commented on src/pages/PreviousMeeting.tsx
> +  const pageData = conversation.slice(startPage, endPage);
다음부턴 lib에 빼겠습니다. 하지만 현재는 페이지네이션 구현 방법을 바꿔서 저 코드는 사라졌습니다 !

2024-11-03 15:08 UTC, Y-minseong commented on src/pages/PreviousMeeting.tsx
> +                onClick={() => onNextPage(Math.max(1, currentPage - 1))}
수정했습니다 !

2024-11-03 15:12 UTC, Y-minseong commented on src/pages/conversation/ConversationChatting.tsx
> +}
apis 폴더의 conversation폴더의 dto로 뺐습니다 !
여기에 둔다면 이 페이지에서만 dto형식을 선언해주기 위해서 아닌가요 ?

2024-11-03 15:13 UTC, Y-minseong commented on src/pages/PreviousRoom.tsx
> +                  <TableCell>3일 전</TableCell>
당연합니다 !ㅎㅎ
회의록의 저장이 완료되면 정상적으로 작동하게 수정하겠습니다 !

2024-11-04 03:36 UTC, Y-minseong commented on src/pages/PreviousRoom.tsx
> +      </div>
수정했습니다 !

2024-11-04 03:36 UTC, Y-minseong commented on src/pages/PreviousRoom.tsx
> +  const pageCount = 8;
수정했습니다 채승님 건우님 감사합니다 !

2024-11-04 03:36 UTC, Y-minseong commented on src/pages/PreviousRoom.tsx
> +  // const [currentPage, setCurrentPage] = useState(1);
ㅎㅎ ,, 실수했네여

2024-11-04 03:45 UTC, Y-minseong commented on src/pages/PreviousRoom.tsx
> +  }
로딩중일때와 데이터가 없을때를 따로 구분했습니다 !! isError는 후에 에러페이지를 따로 파일로 분리해 만든 후 작업하겠습니다 !