feat: Display Unread Message Count When Chat Is Closed
jungle-6-3/code-sync-fe pull request #82
Opened 2024-11-04 05:24 UTC by Y-minseong

## 주요 변경사항
- 채팅창이 닫혀있고 상대방에게 채팅이 왔을 시 count를 띄워주기. 
## 리뷰어에게...
- 새로고침하면 count를 DB에 저장하지 못해서 count가 초기화됩니다. 일단 keep해놓을까요 백에게 이야기해서 진행해볼까요 ? 아니면 DB에 저장하는 방법 말고도 새로운 방법이 있을까요 ?
## 관련 이슈

closes - #80

2024-11-04 05:48 UTC, loopy-lim requested changes
몇개는 수정해주시면 좋을 것 같아요~

2024-11-04 05:48 UTC, loopy-lim commented on src/components/GNB/LeftGNB.tsx
> +  const socket = SocketManager.getInstance().socketIOSocket;
그... socket사용하실 때 어떻게 사용하면 좋을지 다른 PR을 한번 확인해주면 좋을꺼 같아요 ^^

2024-11-04 05:48 UTC, loopy-lim commented on src/components/GNB/LeftGNB.tsx
> +            )}
shadcn에 뱃지 한번 찾아보세요

2024-11-04 05:48 UTC, loopy-lim commented on src/components/GNB/LeftGNB.tsx
>    return (
leftGNB에서 이 코드를 작성하는 것이 좋을지 한번 확인해보면 좋을것 같아요
다른 곳이 있다면 어디가 있을까요?

2024-11-04 05:48 UTC, loopy-lim commented on src/hooks/Conversation/useSaveMeetingMutation.tsx
> +};
일반적으로 useSaveMettingMutation에서 값을 바로 받아서 콜백으로 집어 넣어주는 것보다,
postSaveMeetingApi를 그냥 넣게 되면 추후에 mutate에서 바로 ()를 넣을 수 있어요

2024-11-04 06:58 UTC, Y-minseong commented on src/components/GNB/LeftGNB.tsx
> +            )}
수정했습니다 !!

2024-11-05 01:41 UTC, pigpgw commented on src/components/GNB/LeftGNB.tsx
> +  const socket = SocketManager.getInstance().socketIOSocket;
- [링크](https://github.com/jungle-6-3/code-sync-fe/pull/76)

2024-11-05 01:54 UTC, pigpgw commented on src/components/PreviousRoom/Pagination.tsx
> +    // TODO: toString()말고도 몇개있음. 나중에 찾아보기(민성)
👍

2024-11-05 01:54 UTC, pigpgw commented on src/components/ui/badge.tsx
> +import * as React from "react"
필요한가요???

2024-11-05 05:19 UTC, Y-minseong commented on src/components/GNB/LeftGNB.tsx
> +  const socket = SocketManager.getInstance().socketIOSocket;
수정했습니다 ! 친절히 링크 달아주셔서 감사합니다 ! 덕분에 편하게 찾아봤어요 !

2024-11-05 05:22 UTC, Y-minseong commented on src/components/ui/badge.tsx
> +import * as React from "react"
shadcn의 컴포넌트를 가져온거라 아마 필요하지 않을까요 ?

2024-11-05 05:22 UTC, Y-minseong commented on src/components/PreviousRoom/Pagination.tsx
> +    // TODO: toString()말고도 몇개있음. 나중에 찾아보기(민성)
점점 많아지는 TODO ,,

2024-11-05 05:58 UTC, Y-minseong commented on src/components/GNB/LeftGNB.tsx
>    return (
hooks/Conversation에 useChattingCountEvent로 분리했습니다 !

2024-11-05 06:00 UTC, loopy-lim commented on src/components/GNB/LeftGNB.tsx
>    return (
훅으로 분리하는 것은 좋아요! 그럼에도, 어디쪽에서 그 훅을 선언하는 것이 좋을지 고민해보면 좋을 것 같아요

2024-11-05 06:05 UTC, Y-minseong commented on src/hooks/Conversation/useSaveMeetingMutation.tsx
> +};
수정했습니다 !! 후에 이 Mutation을 사용할진 모르겠지만 구조분해 할당으로 인자 넣겠습니다 !

2024-11-05 06:35 UTC, loopy-lim approved these changes
일단 어느정도는 좋습니다.
이름만 변경하시고 merge해도 좋을 것 같습니다.

2024-11-05 06:35 UTC, loopy-lim commented on src/components/GNB/LeftGNB.tsx
> +  const isMessage = sectionSelectStore((state) => state.leftSection);
이름에 is가 붙는 다는 것은 boolean을 뜻하는 것과 유사합니다.
하지만 여기서 기대되는 값은 folder즉, string 값이므로 변수명을 바꾸는 것을 추천합니다.

2024-11-05 06:35 UTC, loopy-lim commented on src/hooks/Conversation/useChattingCountEvent.tsx
> +  }, [isMessage]);
이 로직을 좀 더 발전하면 꺼지거나 켜졌을 때 0으로 초기화 되는 것이 고쳐지지 않을까요?

2024-11-05 07:22 UTC, Y-minseong commented on src/components/GNB/LeftGNB.tsx
>    return (
코드 칠 때 생각없이 치지않고 꾸준히 생명주기 생각하면서 치고 제 코드에 확신을 가지겠습니다 ! 덕분에 도움 많이 되었습니다 ㅎㅎ

2024-11-05 07:24 UTC, Y-minseong commented on src/components/GNB/LeftGNB.tsx
> +  const isMessage = sectionSelectStore((state) => state.leftSection);
currentLeftSection으로 수정했습니다 ! boolean에서 string으로 바뀌었으면 변수명도 조정했어야 했는데 빼먹었네요 ! 짚어주셔서 감사합니다 !

2024-11-05 10:03 UTC, Y-minseong commented on src/hooks/Conversation/useChattingCountEvent.tsx
> +  }, [isMessage]);
if (currentLeftSection == 'chat')을 추가했어야했는데,, 그래야지 chatting창이 켜졌을때 0으로 초기화되면서 Badge가 사라지는데ㅠ 자꾸 이런걸 놓치네요ㅠㅠ

2024-11-05 10:12 UTC, merged